# Generated by Django 3.0.3 on 2020-03-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJgramapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='vjti.jpg', upload_to='post_pics'),
        ),
    ]
