# Generated by Django 3.0.3 on 2020-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VJgramapp', '0004_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date_created',
        ),
        migrations.AddField(
            model_name='like',
            name='l',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
