# Generated by Django 3.0.3 on 2020-03-25 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VJgramapp', '0005_auto_20200318_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user2',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
