# Generated by Django 3.0.5 on 2020-04-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VJgramapp', '0009_auto_20200403_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
