# Generated by Django 3.0.5 on 2020-04-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200417_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
    ]
