# Generated by Django 3.0.5 on 2020-04-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
    ]
