# Generated by Django 3.0.5 on 2020-04-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_groupmember_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chat.Group'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupname', to='chat.Group'),
        ),
    ]
