# Generated by Django 3.0.5 on 2020-04-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200417_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
    ]
