# Generated by Django 3.0.5 on 2020-04-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200417_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTo',
        ),
    ]
