# Generated by Django 3.0.5 on 2020-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200317_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='vjti.jpg', upload_to='media/profile_pics'),
        ),
    ]
